name: Build Kernel

on:
  push:
    branches: main

env:
  KERNEL: https://github.com/arcovery/android_kernel_xiaomi_sm8150.git
  KERNEL_BRANCH: dev

jobs:
  build: 
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Setup Envoirment
         run: |
            sudo -E apt-get -qq install git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison device-tree-compiler
            sudo -E apt-get -qq --reinstall install python3-minimal
            sudo -E apt-get -qq install -y libfdt-dev
       - name: Clone Kernel
         run: |
            git clone $KERNEL --depth=1 -b $KERNEL_BRANCH kernel
            
       - name: Building
         run: |
            cd kernel
            bash build.sh
            
       - uses: actions/upload-artifact@v3
         with:
          name: Kernel
          path: kernel/flash_zip/*.zip
          
